# /coder/apps/config.yaml
apps:
  # Name of application in launcher. Name may consist of alphanumeric
  # characters, dashes, underscores. Names must begin with an alphanumeric
  # character. Names must be unique per application. Required.
  - name: Apache Airflow
    # Application scheme - must be http or https. Required.
    scheme: http
    # Application port. Required.
    port: 8080
    # Host of the application to use when dialing. Defaults to localhost.
    # Optional.
    host: "localhost"
    # Working directory for the start command. Required.
    working-directory: /home/coder
    # File path to icon used in application launcher. Icons should be either
    # PNG, SVG, or JPG. Required.
    icon-path: /coder/apps/airflow_logo_2.png
    # Command to start the application. Required.
    command: airflow
    # Array of arguments for command. Optional.
    args: ["webserver", "-p", "8080"]
    # Health checks to get running application status. Can use exec or http
    # health checks to localhost. Optional, but we recommend specifying a
    # health check. If you don't supply one, then an http request is sent to
    # the application root path "/".