# /coder/apps/config.yaml
apps:
  - name: code-server
    scheme: http
    port: 8080
    host: "localhost"
    working-directory: /home/coder 
    icon-path: /coder/apps/code-server-icon.png
    command:  /usr/bin/code-server
    args: [
      "--auth=none"
    ]
    health-check:
      http:
        scheme: "http"
        path: "/"
        port: 8080
